<html>
    <head>
    <title>会员中心</title>
    </head>
    <body>
        <p><h2>会员信息</h2></p>
        <p>姓名：{{tname}}</p>
        <p>年龄：{{tage}}</p>
        <p>博客：{{tblog}}</p>
        <p>QQ：{{tqq}}</p>
    </body>
</html>
